SAMPLE_POSTS = [
    "Mình mới học Python, mọi người cho hỏi nên bắt đầu từ tài liệu nào?",
    "Ai có bài tập lập trình Python cơ bản cho người mới không?",
    "Cần tìm khóa học xử lý ngôn ngữ tự nhiên bằng Python.",
    "Bán laptop Dell cũ, máy còn tốt, phù hợp học tập và làm việc.",
    "Mình muốn mua sách lập trình Python, bạn nào có để lại giá rẻ.",
    "Hỏi cách sửa lỗi khi chạy chương trình Python trên Windows.",
    "Game này chơi giải trí khá vui, có ai lập đội chơi cùng không?",
    "Thanh lý tai nghe còn bảo hành, âm thanh tốt, giá sinh viên.",
    "Chia sẻ kinh nghiệm học tiếng Anh mỗi ngày hiệu quả.",
    "Cần hỏi địa chỉ mua bàn phím cơ giá tốt ở Hà Nội.",
    "Mọi người cho xin tài liệu ôn thi cơ sở dữ liệu.",
    "Có ai biết cách cài đặt môi trường lập trình web bằng Python không?",
    "Tài khoản của mình không đăng nhập được, ai biết nguyên nhân không?",
    "Cuối tuần này có bộ phim nào hay để xem cùng bạn bè không?",
    "Mình cần bán màn hình máy tính 24 inch, còn dùng tốt.",
    "Xin kinh nghiệm làm bài thuyết trình môn trí tuệ nhân tạo.",
]


TRAINING_DATA = [
    ("hoc_tap", "Mình mới học Python cơ bản, cần tài liệu cho người mới bắt đầu."),
    ("hoc_tap", "Ai có bài tập lập trình Python và lời giải không?"),
    ("hoc_tap", "Cho mình xin giáo trình xử lý ngôn ngữ tự nhiên."),
    ("hoc_tap", "Cần hỏi cách cài đặt môi trường học lập trình web."),
    ("hoc_tap", "Chia sẻ kinh nghiệm học tiếng Anh và ôn thi hiệu quả."),
    ("hoc_tap", "Mình cần tài liệu cơ sở dữ liệu để ôn tập."),
    ("hoc_tap", "Xin kinh nghiệm làm bài thuyết trình môn trí tuệ nhân tạo."),
    ("hoc_tap", "Bạn nào có đề cương ôn thi mạng máy tính cho mình xin."),
    ("hoc_tap", "Mình đang học HTML CSS và cần bài thực hành đơn giản."),
    ("hoc_tap", "Có khóa học miễn phí nào về lập trình web cho sinh viên không?"),
    ("hoc_tap", "Mình cần tài liệu học Python nâng cao và ví dụ dễ hiểu."),
    ("hoc_tap", "Ai có bài giảng cơ sở dữ liệu quan hệ cho mình tham khảo không?"),
    ("hoc_tap", "Cần nhóm học chung môn xử lý ngôn ngữ tự nhiên cuối kỳ."),
    ("hoc_tap", "Bạn nào biết cách làm bài tập thuật toán thì chỉ giúp mình."),
    ("hoc_tap", "Cho mình xin tài liệu ôn thi lập trình hướng đối tượng."),
    ("hoc_tap", "Mình muốn học thêm về học máy nhưng chưa biết bắt đầu từ đâu."),
    ("hoc_tap", "Có ai chia sẻ kinh nghiệm làm đồ án Python được không?"),
    ("hoc_tap", "Mình cần ví dụ về phân loại văn bản bằng Naive Bayes."),
    ("hoc_tap", "Xin link bài tập thực hành HTML CSS cho người mới."),
    ("hoc_tap", "Bạn nào có giáo trình trí tuệ nhân tạo bản dễ đọc không?"),
    ("hoc_tap", "Mình cần đề cương ôn thi môn mạng máy tính để học cuối kỳ."),
    ("hoc_tap", "Ai có bài giảng cơ sở dữ liệu quan hệ gửi mình tham khảo với."),
    ("hoc_tap", "Bạn nào có tài liệu thuật toán sắp xếp và tìm kiếm không?"),
    ("hoc_tap", "Mình muốn xin bài mẫu đồ án phân loại văn bản để học cách làm."),
    ("hoc_tap", "Có nhóm học chung môn lập trình hướng đối tượng tuần này không?"),
    ("hoc_tap", "Mình cần ôn tập lý thuyết Naive Bayes trước khi bảo vệ đồ án."),
    ("hoc_tap", "Bạn nào có lời giải bài tập lập trình Python cho mình tham khảo không?"),
    ("giai_tri", "Game này chơi giải trí rất vui vào cuối tuần."),
    ("giai_tri", "Có ai xem phim mới ra rạp chưa, nội dung khá hay."),
    ("giai_tri", "Tối nay lập đội chơi game cùng nhau nhé."),
    ("giai_tri", "Bài nhạc này nghe thư giãn sau giờ học."),
    ("giai_tri", "Mọi người đề xuất truyện hay để đọc lúc rảnh."),
    ("giai_tri", "Chia sẻ quán cà phê có nhạc sống cuối tuần."),
    ("giai_tri", "Cuối tuần này có chương trình ca nhạc nào thú vị không?"),
    ("giai_tri", "Ai chơi bóng đá tối nay thì đăng ký tham gia nhé."),
    ("giai_tri", "Mình muốn tìm phim hài nhẹ nhàng để xem sau giờ làm."),
    ("giai_tri", "Có sự kiện cosplay nào diễn ra ở trung tâm thương mại không?"),
    ("giai_tri", "Tối nay có ai chơi liên quân giải trí cùng mình không?"),
    ("giai_tri", "Mọi người gợi ý bộ phim kinh dị nào đáng xem không?"),
    ("giai_tri", "Cuối tuần đi xem ca nhạc ở công viên có vui không?"),
    ("giai_tri", "Ai có playlist nhạc thư giãn để nghe khi nghỉ ngơi không?"),
    ("giai_tri", "Mình muốn tìm truyện tranh hài để đọc sau giờ học."),
    ("giai_tri", "Có giải bóng đá sinh viên nào diễn ra tuần này không?"),
    ("giai_tri", "Rủ mọi người đi xem phim hoạt hình mới ra rạp."),
    ("giai_tri", "Quán cà phê này có không gian đẹp và nhạc nhẹ rất chill."),
    ("giai_tri", "Tối thứ bảy lập đội chơi game sinh tồn cho vui nhé."),
    ("giai_tri", "Ai biết sự kiện âm nhạc miễn phí ở gần trường không?"),
    ("giai_tri", "Mọi người có playlist nhạc thư giãn nào nghe lúc nghỉ ngơi không?"),
    ("giai_tri", "Sự kiện âm nhạc cuối tuần ở gần trường nghe nói rất vui."),
    ("giai_tri", "Ai muốn đi xem chương trình hài tối nay thì đăng ký nhé."),
    ("giai_tri", "Có trò chơi sinh tồn nào nhẹ máy để giải trí sau giờ học không?"),
    ("giai_tri", "Mình muốn tìm quán trà sữa có không gian đẹp để tám chuyện."),
    ("giai_tri", "Sự kiện cosplay cuối tuần ở trung tâm thương mại rất đông vui."),
    ("giai_tri", "Tối nay rủ nhau xem phim hài và nghe nhạc thư giãn nhé."),
    ("hoi_dap", "Tài khoản của mình không đăng nhập được, ai biết nguyên nhân không?"),
    ("hoi_dap", "Máy tính bị mất kết nối wifi thì kiểm tra chỗ nào trước?"),
    ("hoi_dap", "Lỗi không mở được file PDF thì xử lý như thế nào?"),
    ("hoi_dap", "Ai biết cách đổi mật khẩu email thì hướng dẫn giúp mình."),
    ("hoi_dap", "Điện thoại không nhận sạc, có phải hỏng pin không?"),
    ("hoi_dap", "Mình cần hỏi thủ tục xin giấy xác nhận sinh viên."),
    ("hoi_dap", "Không nghe được âm thanh trên máy tính thì sửa ra sao?"),
    ("hoi_dap", "Có ai biết vì sao trình duyệt không tải được ảnh không?"),
    ("hoi_dap", "Làm sao để khôi phục bài viết đã xóa nhầm trên diễn đàn?"),
    ("hoi_dap", "Ai gặp lỗi màn hình xanh Windows thì cho mình xin cách sửa."),
    ("hoi_dap", "Mình quên mật khẩu tài khoản diễn đàn thì lấy lại bằng cách nào?"),
    ("hoi_dap", "Không gửi được email kèm file thì cần kiểm tra phần nào?"),
    ("hoi_dap", "Máy in không nhận lệnh in thì xử lý ra sao?"),
    ("hoi_dap", "Làm sao để đổi tên hiển thị trên diễn đàn?"),
    ("hoi_dap", "Điện thoại bị nóng khi sạc có nguy hiểm không?"),
    ("hoi_dap", "Có ai biết cách sửa lỗi không kết nối được máy chiếu không?"),
    ("hoi_dap", "Mình không tải được tài liệu trên hệ thống học tập thì làm sao?"),
    ("hoi_dap", "Lỗi bàn phím không gõ được tiếng Việt thì sửa thế nào?"),
    ("hoi_dap", "Ai biết cách khôi phục mật khẩu wifi đã lưu trên máy tính không?"),
    ("hoi_dap", "Tại sao trình duyệt báo lỗi chứng chỉ bảo mật khi đăng nhập?"),
    ("hoi_dap", "Điện thoại báo pin ảo và nhanh hết pin thì có phải hỏng pin không?"),
    ("hoi_dap", "Mình cần hỏi thủ tục xin giấy xác nhận sinh viên online."),
    ("hoi_dap", "Không tải được file bài giảng trên hệ thống thì xử lý thế nào?"),
    ("hoi_dap", "Tài khoản diễn đàn bị khóa thì liên hệ ai để mở lại?"),
    ("hoi_dap", "Máy tính không nhận ổ cứng di động thì kiểm tra ra sao?"),
    ("hoi_dap", "Không tải được tài liệu trên hệ thống học tập thì cần báo cho ai?"),
    ("hoi_dap", "Ai biết vì sao tài khoản email không gửi được mã xác nhận không?"),
    ("mua_ban", "Bán laptop cũ giá rẻ, máy còn tốt cho sinh viên."),
    ("mua_ban", "Mình muốn mua sách lập trình Python đã qua sử dụng."),
    ("mua_ban", "Thanh lý tai nghe còn bảo hành, âm thanh tốt."),
    ("mua_ban", "Cần mua bàn phím cơ giá tốt ở Hà Nội."),
    ("mua_ban", "Bán điện thoại cũ, pin còn khỏe, giá thương lượng."),
    ("mua_ban", "Ai có màn hình máy tính cũ cần bán không?"),
    ("mua_ban", "Mình cần bán màn hình máy tính 24 inch, còn dùng tốt."),
    ("mua_ban", "Thanh lý balo laptop mới dùng vài lần, giá sinh viên."),
    ("mua_ban", "Cần mua chuột không dây còn bảo hành, ưu tiên khu vực gần trường."),
    ("mua_ban", "Bán ghế học tập còn chắc chắn, ai cần thì nhắn mình."),
    ("mua_ban", "Cần bán máy tính bảng cũ, màn hình đẹp, pin ổn."),
    ("mua_ban", "Mình muốn mua laptop văn phòng giá dưới năm triệu."),
    ("mua_ban", "Thanh lý sách cơ sở dữ liệu và sách thuật toán giá rẻ."),
    ("mua_ban", "Bán loa bluetooth nhỏ gọn, âm thanh hay, còn bảo hành."),
    ("mua_ban", "Ai cần mua máy in cũ dùng tốt thì liên hệ mình."),
    ("mua_ban", "Cần mua ổ cứng di động dung lượng cao giá hợp lý."),
    ("mua_ban", "Bán điện thoại Android cũ, ngoại hình đẹp, pin tốt."),
    ("mua_ban", "Thanh lý bàn học gỗ còn mới, phù hợp phòng trọ sinh viên."),
    ("mua_ban", "Mình cần mua webcam học online, ưu tiên còn bảo hành."),
    ("mua_ban", "Bán combo chuột và bàn phím không dây giá sinh viên."),
    ("mua_ban", "Mình cần mua sách lập trình Python cũ giá rẻ để học."),
    ("mua_ban", "Bán bộ sách thuật toán và cơ sở dữ liệu đã qua sử dụng."),
    ("mua_ban", "Cần mua ổ cứng di động cũ dung lượng cao, giá hợp lý."),
    ("mua_ban", "Thanh lý laptop văn phòng pin ổn, phù hợp sinh viên."),
    ("mua_ban", "Bán máy chiếu mini còn mới, dùng tốt cho thuyết trình."),
    ("mua_ban", "Cần mua máy tính cũ cấu hình ổn để học lập trình Python."),
    ("mua_ban", "Bán tai nghe bluetooth mới mua, âm thanh tốt, giá thương lượng."),
]


CATEGORY_NAMES = {
    "hoc_tap": "Học tập",
    "giai_tri": "Giải trí",
    "hoi_dap": "Hỏi đáp",
    "mua_ban": "Mua bán",
}
